[tool.poetry]
name = "kae-dbt"
version = "0.2.0"
description = "KAE utilities for dbt"
authors = ["Marcos Alcozer <marcos@alcozer.dev>", "Zander Stachniak <zander@alcozer.dev>"]
readme = "README.md"
packages = [{include = "kae_dbt"}]

[tool.poetry.dependencies]
python = "^3.9.10"
dbt-bigquery = "1.6.5"

[tool.poetry.group.dev.dependencies]
sqlfluff = "2.3.2"
sqlfluff-templater-dbt = "2.3.2"
black = "23.9.1"
ruff = "0.0.290"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
